# we still have to use compose v1 since the app requires LINKed environments

guacd:
    image: glyptodon/guacd

guacamole:
    image: glyptodon/guacamole
    links:
        - guacd
        - mysql
    environment:
        - MYSQL_DATABASE=guacamole_db
        - MYSQL_USER=guacamole_user
        - MYSQL_PASSWORD=guacamole_pass
    ports:
        - 8080:8080

mysql:
    image: mysql:latest
    volumes:
        - ./mysql_data:/var/lib/mysql
        - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=guacamole_db
        - MYSQL_USER=guacamole_user
        - MYSQL_PASSWORD=guacamole_pass
